# Generated by Django 5.2.5 on 2025-11-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_customer_email_verified_customer_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='refund_status',
            field=models.CharField(choices=[('none', 'None'), ('in_process', 'In Process'), ('refunded', 'Refunded')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('complete', 'Complete'), ('cancel', 'Cancel')], default='Pending', max_length=20),
        ),
    ]
