# .render.yaml
services:
  - type: web
    name: ticket-anywhere-backend
    env: python
    pythonVersion: 3.12
    buildCommand: cd Ticket-Anywhere-Backend && pip install -r requirements.txt && python manage.py migrate
    startCommand: cd Ticket-Anywhere-Backend && gunicorn ticketanywhere.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120
    autoDeploy: true
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        fromEnv: DJANGO_SECRET_KEY
      - key: ALLOWED_HOSTS
        value: your-app-name.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: ticket-anywhere-db
          property: connectionString

databases:
  - name: ticket-anywhere-db
    plan: free
    region: ohio
